---
- name: Install Bitcoin Core and friends
  pacman:
    name:
      - bitcoin-daemon
      - bitcoin-tx

- name: Get hidden service URL
  slurp:
    src: /var/lib/tor/bitcoin-service/hostname
  register: bitcoin_onion_url

- name: Configure bitcoind
  template:
    src: templates/bitcoin.conf.j2
    dest: /etc/bitcoin/bitcoin.conf
    mode: 0644
  notify:
    - Restart bitcoind

- name: Enable and start bitcoind
  systemd:
    name: bitcoind
    enabled: yes
    state: started
