- name: User management
  hosts: all
  gather_facts: false
  become: yes
  vars:
    user: fionn
    password_salt: "n3mBfO4IivEt5zMI"
    password_string: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35393839373235643461343434326265636430343662636431623664633464646237653032613766
          6561343734643932303435643262393232616532643161310a383461396264623839633462353862
          30656132336134393934346631383863653961346530623331383239613464613236653436333365
          3263303137646366320a356661383535326438303238323536376534376664663564383632396165
          6133

  tasks:

    - name: Test username
      ping:
      ignore_unreachable: true
      ignore_errors: true
      changed_when: false
      register: ssh_test
      become: no

    - name: Fall back to alarm user
      when: ssh_test.unreachable is defined
      connection: local
      become: no
      set_fact:
        ansible_user: alarm
        ansible_ssh_pass: alarm
        ansible_become_password: alarm

    - name: Create user {{ user }}
      when: ssh_test.unreachable is defined
      user:
        name: "{{ user }}"
        groups: wheel
        append: yes
        password: "{{ password_string | string | password_hash('sha512', password_salt) }}"

    - name: Revert to user {{ user }}
      set_fact:
        ansible_user: "{{ user }}"
        ansible_ssh_password: "{{ password_string }}"
        ansible_become_password: "{{ password_string }}"

    - name: Set authorized keys
      become: no
      authorized_key:
        user: "{{ user }}"
        key: https://github.com/{{ user }}.keys
        exclusive: yes

    - name: Ensure {{ user }} has correct password
      user:
        name: "{{ user }}"
        groups: wheel
        append: yes
        password: "{{ password_string | string | password_hash('sha512', password_salt) }}"

    - name: Destroy alarm user
      user:
        name: alarm
        state: absent
        remove: yes

- name: Update and configure baseline system
  hosts: all
  become: yes
  vars:
    hostname: macak

  tasks:

    - name: Start entropy daemon
      systemd:
        name: haveged.service
        state: started
        enabled: yes

    - name: Set hostname with systemd
      hostname:
        name: "{{ hostname }}"
        use: systemd

    - name: Set hosts
      blockinfile:
        path: /etc/hosts
        block: |
          127.0.0.1 localhost.localdomain localhost
          127.0.0.1 {{ hostname }}.localdomain {{ hostname }}
          ::1 localhost.localdomain localhost
          ::1 {{ hostname }}.localdomain {{ hostname }}

    - name: Generate locale
      locale_gen:
        name: en_HK.UTF-8

    - name: Sync time
      systemd:
        name: systemd-timesyncd.service
        state: started
        enabled: yes

    - name: Configure Pacman color
      replace:
        dest: /etc/pacman.conf
        regexp: "^#Color"
        replace: Color

    - name: Configure Pacman parallel downloads
      replace:
        dest: /etc/pacman.conf
        regexp: "^#ParallelDownloads"
        replace: ParallelDownloads

    - name: Configure Pacman candy
      lineinfile:
        path: /etc/pacman.conf
        insertafter: ParallelDownloads
        line: ILoveCandy

    - name: Update and upgrade packages
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install basic packages
      pacman:
        name:
          - sudo
          - git
          - man
          - vim
          - stow
          - ripgrep
          - tree
          - python-pylint
          - mypy
          - terminus-font
          - htop
          - wget
          - ncdu
          - bash-completion
          - pkgfile
          - make
          - tmux

    - name: Set console font
      lineinfile:
        path: /etc/vconsole.conf
        create: yes
        line: "FONT=ter-124n"
        mode: 0644

- name: Configure wireless networking
  hosts: all
  become: yes
  vars:
    ssid: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61386235613366353631663266623537313833393463343438653835643966386434353835346164
          3336393431393332653061626466626363336265303165300a306631303536353935646439333765
          39653430633930343532396539636536613138363135326336663239396434363865646366336638
          3633373732666434320a386561373361653335633964343361653866376661626661646232383566
          6532
    psk: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37383030313239343663663761333266313862656561306239393333646163613135343133306439
          6564633464323261343233313732386133663932636562340a353463353535666233303737373066
          38643065356362356434363034613163373432643333623064356161393736326431373230313736
          6633363834616262610a306533353530623536376133343933383539656535353666346437663066
          65343339353034316232653135626136343730366133323833626366383532656336303334353865
          39666130656661353634313033306561396331626366303866653036633539363237643466653565
          31376434316637376162663865633864316237396264663033363563373966343333396665366237
          35303361343639393132

  tasks:

    - name: Add network to wpa_supplicant
      template:
        src: templates/wpa_supplicant-wlan0.conf.j2
        dest: /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
        mode: 0644

    - name: Configure networkd to manage wlan0
      copy:
        src: files/wlan0.network
        dest: /etc/systemd/network/wlan0.network
        mode: 0644

    - name: Enable wpa_supplicant
      systemd:
        name: wpa_supplicant@wlan0.service
        state: started
        enabled: yes

    - name: Enable networkd
      systemd:
        name: systemd-networkd.service
        state: started
        enabled: yes

- name: Configure home
  hosts: all

  tasks:

    - name: Get dotfiles
      git:
        repo: https://github.com/fionn/.dotfiles.git
        dest: ~/.dotfiles
        accept_hostkey: yes
        recursive: yes
        version: master

    - name: Remove conflicting dotfiles
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - .bashrc
        - .bash_profile

    - name: Stow dotfiles
      command:
        cmd: stow {{ item }}
        chdir: ~/.dotfiles
        creates: ~/.pam_environment
      loop:
        - vim
        - bash
        - git
        - inputrc
        - mypy
        - pam

- name: Reboot
  hosts: all
  become: yes

  tasks:

    - name: Reboot
      reboot:
