---
- name: Get dotfiles
  git:
    repo: https://github.com/{{ github_username }}/.dotfiles.git
    dest: ~/.dotfiles
    accept_hostkey: yes
    recursive: yes
    version: master
    force: yes

- name: Check for conflicts
  stat:
    path: "{ item }"
  loop:
    - .bashrc
    - .bash_profile
  register: conflicts

- name: Remove conflicting dotfiles
  file:
    path: "{{ item.path }}"
    state: absent
  when: item.stat.islnk is defined and not item.stat.islnk
  loop: "{{ conflicts.results }}"

- name: Create configuration directory
  file:
    path: ~/.config
    state: directory
    mode: "0755"

- name: Stow dotfiles
  command:
    cmd: stow {{ item }}
    chdir: ~/.dotfiles
    creates: ~/.bash_profile
  loop:
    - vim
    - bash
    - git
    - inputrc
    - mypy
    - pam
